app/Http/routes.php
<?php

/**
 * Switch between the included languages
 */
require(__DIR__ . "/Routes/Global/Lang.php");

/**
 * Frontend Routes
 * Namespaces indicate folder structure
 */
$router->group(['namespace' => 'Frontend'], function () use ($router)
{
	require(__DIR__ . "/Routes/Frontend/Frontend.php");
	require(__DIR__ . "/Routes/Frontend/Access.php");
});

/**
 * Backend Routes
 * Namespaces indicate folder structure
 */
$router->group(['namespace' => 'Backend'], function () use ($router)
{
	$router->group(['prefix' => 'admin', 'middleware' => 'auth'], function () use ($router)
	{
		/**
		 * These routes need view-backend permission (good if you want to allow more than one group in the backend, then limit the backend features by different roles or permissions)
		 *
		 * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
		 */
		$router->group(['middleware' => 'access.routeNeedsPermission:view-backend'], function () use ($router)
		{
			require(__DIR__ . "/Routes/Backend/Dashboard.php");
			require(__DIR__ . "/Routes/Backend/Access.php");
		});
	});
});

app/Models/Access/Permission/Permission.php
<?php namespace App\Models\Access\Permission;

use Illuminate\Database\Eloquent\Model;
use App\Models\Access\Permission\Traits\Attribute\PermissionAttribute;
use App\Models\Access\Permission\Traits\Relationship\PermissionRelationship;

/**
 * Class Permission
 * @package App\Models\Access\Permission
 */
class Permission extends Model {

	use PermissionRelationship, PermissionAttribute;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table;

	/**
	 * The attributes that are not mass assignable.
	 *
	 * @var array
	 */
	protected $guarded = ['id'];

	/**
	 *
	 */
	public function __construct()
	{
		$this->table = config('access.permissions_table');
	}
}

app/Models/Access/Permission/PermissionDependency.php
<?php namespace App\Models\Access\Permission;

use Illuminate\Database\Eloquent\Model;
use App\Models\Access\Permission\Traits\Relationship\PermissionDependencyRelationship;

/**
 * Class PermissionDependency
 * @package App\Models\Access\Permission
 */
class PermissionDependency extends Model {

    use PermissionDependencyRelationship;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table;

    /**
     * The attributes that are not mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];

    /**
     *
     */
    public function __construct()
    {
        $this->table = config('access.permission_dependencies_table');
    }
}

app/Models/Access/Permission/PermissionGroup.php
<?php namespace App\Models\Access\Permission;

use Illuminate\Database\Eloquent\Model;
use App\Models\Access\Permission\Traits\Attribute\PermissionGroupAttribute;
use App\Models\Access\Permission\Traits\Relationship\PermissionGroupRelationship;

/**
 * Class PermissionGroup
 * @package App\Models\Access\Permission
 */
class PermissionGroup extends Model {

    use PermissionGroupRelationship, PermissionGroupAttribute;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table;

    /**
     * The attributes that are not mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];

    /**
     *
     */
    public function __construct()
    {
        $this->table = config('access.permission_group_table');
    }
}

app/Models/Access/Permission/Traits/Attribute/PermissionAttribute.php
<?php namespace App\Models\Access\Permission\Traits\Attribute;

/**
 * Class PermissionAttribute
 * @package App\Models\Access\Permission\Traits\Attribute
 */
trait PermissionAttribute {

    /**
     * @return bool
     */
    public function isSystem() {
        return $this->system == 1 ? true : false;
    }

    /**
     * @return string
     */
    public function getSystemLabelAttribute() {
        switch($this->system) {
            case 0:
                return '<span class="label label-success">No</span>';

            case 1:
                return '<span class="label label-danger">Yes</span>';
        }
    }

    /**
     * @return string
     */
    public function getEditButtonAttribute() {
        if (access()->can('edit-permissions'))
            return '<a href="'.route('admin.access.roles.permissions.edit', $this->id).'" class="btn btn-xs btn-primary tooltips" data-container="body" data-original-title="' . trans('crud.edit_button') . '"  data-placement="top"><i class="fa fa-pencil"></i></a>';
        return '';
    }

    /**
     * @return string
     */
    public function getDeleteButtonAttribute() {
        if (access()->can('delete-permissions'))
            return '<a data-method="delete" class="btn btn-xs btn-danger tooltips" data-container="body" data-original-title="'.trans('crud.delete_button').'"  data-placement="top" onclick="$(this).find(\'form\').submit();"><i class="fa fa-times"></i><form action="'.route('admin.access.roles.permissions.destroy', $this->id).'" method="POST" name="delete_item" style="display:none"><input type="hidden" name="_method" value="delete"><input type="hidden" name="_token" value="'.csrf_token().'"></form></a>';
        return '';
    }

    /**
     * @return string
     */
    public function getActionButtonsAttribute() {
        $buttons = '';
        $buttons .= $this->getEditButtonAttribute();

        //If the permission is not a system item it can be deleted
        if (! $this->isSystem()) {
            $buttons .= ' '.$this->getDeleteButtonAttribute();
        }

        return $buttons;
    }
}

app/Models/Access/User/Traits/Attribute/UserAttribute.php
<?php namespace App\Models\Access\User\Traits\Attribute;

use Illuminate\Support\Facades\Hash;

/**
 * Class UserAttribute
 * @package App\Models\Access\User\Traits\Attribute
 */
trait UserAttribute {

    /**
     * Hash the users password
     *
     * @param $value
     */
    public function setPasswordAttribute($value)
    {
        if (Hash::needsRehash($value))
            $this->attributes['password'] = bcrypt($value);
        else
            $this->attributes['password'] = $value;
    }

    /**
     * @return string
     */
    public function getConfirmedLabelAttribute() {
        if ($this->confirmed == 1)
            return "<label class='label label-success'>Yes</label>";
        return "<label class='label label-danger'>No</label>";
    }

    /**
     * @return mixed
     */
    public function getPictureAttribute() {
        return gravatar()->get($this->email, ['size' => 50]);
    }

    /**
     * @return string
     */
    public function getEditButtonAttribute() {
        if (access()->can('edit-users'))
            return '<a href="'.route('admin.access.users.edit', $this->id).'" class="btn btn-xs btn-primary tooltips" style="color:black;text-decoration:none;" data-container="body" data-original-title="' . trans('crud.edit_button') . '"  data-placement="top"><i class="fa fa-pencil"></i></a> ';
        return '';
    }

    /**
     * @return string
     */
    public function getChangePasswordButtonAttribute() {
        if (access()->can('change-user-password'))
            return '<a href="'.route('admin.access.user.change-password', $this->id).'" class="btn btn-xs btn-info tooltips" style="color:black;text-decoration:none;" data-container="body" data-original-title="' . trans('crud.change_password_button') . '"  data-placement="top"><i class="fa fa-refresh"></i></a>';
        return '';
    }

    /**
     * @return string
     */
    public function getStatusButtonAttribute() {
        switch($this->status) {
            case 0:
                if (access()->can('reactivate-users'))
                    return '<a href="'.route('admin.access.user.mark', [$this->id, 1]).'" class="btn btn-xs btn-success tooltips" style="color:black;text-decoration:none;" data-container="body" data-original-title="' . trans('crud.activate_user_button') . '"  data-placement="top"><i class="fa fa-play"></i></a> ';
                break;

            case 1:
                $buttons = '';

                if (access()->can('deactivate-users'))
                    $buttons .= '<a href="'.route('admin.access.user.mark', [$this->id, 0]).'" class="btn btn-xs btn-warning tooltips" style="color:black;text-decoration:none;" data-container="body" data-original-title="' . trans('crud.deactivate_user_button') . '"  data-placement="top"><i class="fa fa-pause"></i></a> ';

                if (access()->can('ban-users'))
                    $buttons .= '<a href="'.route('admin.access.user.mark', [$this->id, 2]).'" class="btn btn-xs btn-danger tooltips" style="color:black;text-decoration:none;" data-container="body" data-original-title="' . trans('crud.ban_user_button') . '"  data-placement="top"><i class="fa fa-times" ></i></a> ';

                return $buttons;
                break;

            case 2:
                if (access()->can('reactivate-users'))
                    return '<a href="'.route('admin.access.user.mark', [$this->id, 1]).'" class="btn btn-xs btn-success tooltips" style="color:black;text-decoration:none;" data-container="body" data-original-title="' . trans('crud.activate_user_button') . '"  data-placement="top"><i class="fa fa-play"></i></a>';
                break;

            default:
                return '';
                break;
        }

        return '';
    }

    public function getConfirmedButtonAttribute() {
        if (! $this->confirmed)
            if (access()->can('resend-user-confirmation-email'))
                return '<a href="'.route('admin.account.confirm.resend', $this->id).'" class="btn btn-xs btn-success"><i class="fa fa-refresh" data-toggle="tooltip" data-placement="top" title="Resend Confirmation E-mail"></i></a> ';
        return '';
    }

    /**
     * @return string
     */
    public function getDeleteButtonAttribute() {
        if (access()->can('delete-users'))
            return '<a data-method="delete" class="btn btn-xs btn-danger tooltips" style="color:black;text-decoration:none;cursor: pointer" data-container="body" data-original-title="'.trans('crud.delete_button').'"  data-placement="top" onclick="$(this).find(\'form\').submit();"><i class="fa fa-trash"></i><form action="'.route('admin.access.users.destroy', $this->id).'" method="POST" name="delete_item" style="display:none"><input type="hidden" name="_method" value="delete"><input type="hidden" name="_token" value="'.csrf_token().'"></form></a>';
        return '';
    }

    /**
     * @return string
     */
    public function getActionButtonsAttribute() {
        return $this->getEditButtonAttribute().
        $this->getChangePasswordButtonAttribute().' '.
        $this->getStatusButtonAttribute().
        $this->getConfirmedButtonAttribute().
        $this->getDeleteButtonAttribute();
    }
}

app/Http/Controllers/Backend/Access/Permission/PermissionController.php
<?php namespace App\Http\Controllers\Backend\Access\Permission;

use App\Http\Controllers\Controller;
use App\Repositories\Backend\Role\RoleRepositoryContract;
use App\Repositories\Backend\Permission\PermissionRepositoryContract;
use App\Http\Requests\Backend\Access\Permission\EditPermissionRequest;
use App\Http\Requests\Backend\Access\Permission\StorePermissionRequest;
use App\Http\Requests\Backend\Access\Permission\CreatePermissionRequest;
use App\Http\Requests\Backend\Access\Permission\UpdatePermissionRequest;
use App\Http\Requests\Backend\Access\Permission\DeletePermissionRequest;
use App\Repositories\Backend\Permission\Group\PermissionGroupRepositoryContract;

/**
 * Class PermissionController
 * @package App\Http\Controllers\Access
 */
class PermissionController extends Controller {

	/**
	 * @var RoleRepositoryContract
	 */
	protected $roles;

	/**
	 * @var PermissionRepositoryContract
	 */
	protected $permissions;

	/**
	 * @var PermissionGroupRepositoryContract
     */
	protected $groups;

	/**
	 * @param RoleRepositoryContract $roles
	 * @param PermissionRepositoryContract $permissions
	 * @param PermissionGroupRepositoryContract $groups
     */
	public function __construct(RoleRepositoryContract $roles, PermissionRepositoryContract $permissions, PermissionGroupRepositoryContract $groups) {
		$this->roles = $roles;
		$this->permissions = $permissions;
		$this->groups = $groups;
	}

	/**
	 * @return mixed
	 */
	public function index() {
		return view('backend.access.roles.permissions.index')
			->withPermissions($this->permissions->getPermissionsPaginated(50));
	}

	/**
	 * @param CreatePermissionRequest $request
	 * @return mixed
     */
	public function create(CreatePermissionRequest $request) {
		return view('backend.access.roles.permissions.create')
			->withGroups($this->groups->getAllGroups(true))
			->withRoles($this->roles->getAllRoles())
			->withPermissions($this->permissions->getAllPermissions());
	}

	/**
	 * @param StorePermissionRequest $request
	 * @return mixed
     */
	public function store(StorePermissionRequest $request) {
		$this->permissions->create($request->except('permission_roles'), $request->only('permission_roles'));
		return redirect()->route('admin.access.roles.permissions.index')->withFlashSuccess(trans("alerts.permissions.created"));
	}

	/**
	 * @param $id
	 * @param EditPermissionRequest $request
	 * @return mixed
     */
	public function edit($id, EditPermissionRequest $request) {
		$permission = $this->permissions->findOrThrowException($id, true);
		return view('backend.access.roles.permissions.edit')
			->withPermission($permission)
			->withPermissionRoles($permission->roles->lists('id')->all())
			->withGroups($this->groups->getAllGroups(true))
			->withRoles($this->roles->getAllRoles())
			->withPermissions($this->permissions->getAllPermissions())
			->withPermissionDependencies($permission->dependencies->lists('dependency_id')->all());
	}

	/**
	 * @param $id
	 * @param UpdatePermissionRequest $request
	 * @return mixed
     */
	public function update($id, UpdatePermissionRequest $request) {
		$this->permissions->update($id, $request->except('permission_roles'), $request->only('permission_roles'));
		return redirect()->route('admin.access.roles.permissions.index')->withFlashSuccess(trans("alerts.permissions.updated"));
	}

	/**
	 * @param $id
	 * @param DeletePermissionRequest $request
	 * @return mixed
     */
	public function destroy($id, DeletePermissionRequest $request) {
		$this->permissions->destroy($id);
		return redirect()->route('admin.access.roles.permissions.index')->withFlashSuccess(trans("alerts.permissions.deleted"));
	}
}

app/Http/Controllers/Backend/Access/Permission/PermissionGroupController.php
<?php namespace App\Http\Controllers\Backend\Access\Permission;

use App\Http\Controllers\Controller;
use App\Repositories\Backend\Permission\Group\PermissionGroupRepositoryContract;
use App\Http\Requests\Backend\Access\Permission\Group\EditPermissionGroupRequest;
use App\Http\Requests\Backend\Access\Permission\Group\SortPermissionGroupRequest;
use App\Http\Requests\Backend\Access\Permission\Group\StorePermissionGroupRequest;
use App\Http\Requests\Backend\Access\Permission\Group\CreatePermissionGroupRequest;
use App\Http\Requests\Backend\Access\Permission\Group\UpdatePermissionGroupRequest;
use App\Http\Requests\Backend\Access\Permission\Group\DeletePermissionGroupRequest;

/**
 * Class PermissionGroupController
 * @package App\Http\Controllers\Access
 */
class PermissionGroupController extends Controller {

    /**
     * @var PermissionGroupRepositoryContract
     */
    protected $groups;

    /**
     * @param PermissionGroupRepositoryContract $groups
     */
    public function __construct(PermissionGroupRepositoryContract $groups) {
        $this->groups = $groups;
    }

    public function index(){
        return view('backend.access.roles.permissions.groups.index')
            ->withGroups($this->groups->getAllGroups());
    }

    /**
     * @param CreatePermissionGroupRequest $request
     * @return \Illuminate\View\View
     */
    public function create(CreatePermissionGroupRequest $request) {
        return view('backend.access.roles.permissions.groups.create');
    }

    /**
     * @param StorePermissionGroupRequest $request
     * @return mixed
     */
    public function store(StorePermissionGroupRequest $request) {
        $this->groups->store($request->all());
        return redirect()->route('admin.access.roles.permissions.index')->withFlashSuccess(trans("alerts.permissions.groups.created"));
    }

    /**
     * @param $id
     * @param EditPermissionGroupRequest $request
     * @return mixed
     */
    public function edit($id, EditPermissionGroupRequest $request) {
        return view('backend.access.roles.permissions.groups.edit')
            ->withGroup($this->groups->find($id));
    }

    /**
     * @param $id
     * @param UpdatePermissionGroupRequest $request
     * @return mixed
     */
    public function update($id, UpdatePermissionGroupRequest $request) {
        $this->groups->update($id, $request->all());
        return redirect()->route('admin.access.roles.permission-group.index')->withFlashSuccess(trans("alerts.permissions.groups.created"));
    }

    /**
     * @param $id
     * @param DeletePermissionGroupRequest $request
     * @return mixed
     */
    public function destroy($id, DeletePermissionGroupRequest $request) {
        $this->groups->destroy($id);
        return redirect()->route('admin.access.roles.permissions.index')->withFlashSuccess(trans("alerts.permissions.groups.deleted"));
    }

    /**
     * @param SortPermissionGroupRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function updateSort(SortPermissionGroupRequest $request) {
        $this->groups->updateSort($request->get('data'));
        return response()->json(['status' => 'OK']);
    }
}

resources/views/backend/access/banned.blade.php
@extends ('backend.layouts.main')

@section ('title', trans('menus.user_management') . ' | ' . trans('menus.banned_users'))

@section('page-title')
    <h1>
        {{ trans('menus.user_management') }}
        <small>{{ trans('menus.banned_users') }}</small>
    </h1>
@endsection

@section ('breadcrumbs')
    <li><a href="{!!route('backend.dashboard')!!}"><i class="fa fa-dashboard"></i> {{ trans('menus.dashboard') }}</a><i class="fa fa-angle-right"></i></li>
    <li>{!! link_to_route('admin.access.users.index', trans('menus.user_management')) !!}<i class="fa fa-angle-right"></i></li>
    <li class="active">{!! trans('menus.banned_users') !!}</li>
@stop

@section('content')

    @if(Session::get('flash_success'))
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
            @if(is_array(json_decode(Session::get('flash_success'),true)))
                {!! implode('', Session::get('flash_success')->all(':message<br/>')) !!}
            @else
                {!! Session::get('flash_success') !!}
            @endif
        </div>
    @endif
    <div class="portlet light">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-th-list"></i>{!! trans('menus.banned_users') !!}
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""></a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="table-scrollable">
                <table class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>{{ trans('crud.users.id') }}</th>
                        <th>{{ trans('crud.users.name') }}</th>
                        <th>{{ trans('crud.users.email') }}</th>
                        <th>{{ trans('crud.users.confirmed') }}</th>
                        <th>{{ trans('crud.users.roles') }}</th>
                        <th>{{ trans('crud.users.other_permissions') }}</th>
                        <th class="visible-lg">{{ trans('crud.users.created') }}</th>
                        <th class="visible-lg">{{ trans('crud.users.last_updated') }}</th>
                        <th>{{ trans('crud.actions') }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if ($users->count())
                        @foreach ($users as $user)
                            <tr>
                                <td>{!! $user->id !!}</td>
                                <td>{!! $user->name !!}</td>
                                <td>{!! link_to("mailto:".$user->email, $user->email) !!}</td>
                                <td>{!! $user->confirmed_label !!}</td>
                                <td>
                                    @if ($user->roles()->count() > 0)
                                        @foreach ($user->roles as $role)
                                            {!! $role->name !!}<br/>
                                        @endforeach
                                    @else
                                        None
                                    @endif
                                </td>
                                <td>
                                    @if ($user->permissions()->count() > 0)
                                        <a href="javascript:;" data-id="{{$user->id}}" role="button"  class="btn btn-xs red findOtherPermissions">View</a>
                                    @else
                                        <button class="btn btn-xs btn-default disabled">None</button>
                                    @endif
                                </td>
                                <td class="visible-lg">{!! $user->created_at->diffForHumans() !!}</td>
                                <td class="visible-lg">{!! $user->updated_at->diffForHumans() !!}</td>
                                <td>{!! $user->action_buttons !!}</td>
                            </tr>
                        @endforeach
                    @else
                        <td colspan="9">{{ trans('crud.users.no_deactivated_users') }}</td>
                    @endif
                    </tbody>
                </table>

            </div>
        </div>
        <div class="portlet-title">
            <div class="pull-left">
                <h5 class="block">{!! $users->total() !!} {{ trans('crud.users.total') }}</h5>
            </div>

            <div class="pull-right">
                {!! $users->render() !!}
            </div>
        </div>

    </div>
    <div class="clearfix"></div>
    <div id="myModal2" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">Other Permissions</h4>
                </div>
                <div class="modal-body">
                    <p class="per_content">
                        Permissions loading
                    </p>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn green">OK</button>
                </div>
            </div>
        </div>
    </div>
@stop
@section('js')
    <script src="{{asset('backend/js/plugins/userIndex.js')}}" type="text/javascript"></script>
@stop

resources/views/backend/access/deactivated.blade.php
@extends ('backend.layouts.main')

@section ('title', trans('menus.user_management') . ' | ' . trans('menus.deactivated_users'))

@section('page-title')
    <h1>
        {{ trans('menus.user_management') }}
        <small>{{ trans('menus.deactivated_users') }}</small>
    </h1>
@endsection

@section ('breadcrumbs')
    <li><a href="{!!route('backend.dashboard')!!}"><i class="fa fa-dashboard"></i> {{ trans('menus.dashboard') }}</a><i class="fa fa-angle-right"></i></li>
    <li>{!! link_to_route('admin.access.users.index', trans('menus.user_management')) !!}<i class="fa fa-angle-right"></i></li>
    <li class="active">{!! trans('menus.deactivated_users') !!}</li>
@stop

@section('content')
    @if(Session::get('flash_success'))
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
            @if(is_array(json_decode(Session::get('flash_success'),true)))
                {!! implode('', Session::get('flash_success')->all(':message<br/>')) !!}
            @else
                {!! Session::get('flash_success') !!}
            @endif
        </div>
    @endif
    <div class="portlet light">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-th-list"></i>{!! trans('menus.user_management') !!}
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""></a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="table-scrollable">
                <table class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>{{ trans('crud.users.id') }}</th>
                        <th>{{ trans('crud.users.name') }}</th>
                        <th>{{ trans('crud.users.email') }}</th>
                        <th>{{ trans('crud.users.confirmed') }}</th>
                        <th>{{ trans('crud.users.roles') }}</th>
                        <th>{{ trans('crud.users.other_permissions') }}</th>
                        <th class="visible-lg">{{ trans('crud.users.created') }}</th>
                        <th class="visible-lg">{{ trans('crud.users.last_updated') }}</th>
                        <th>{{ trans('crud.actions') }}</th>
                    </tr>
                    </thead>
                    <tbody>
                        @if ($users->count())
                            @foreach ($users as $user)
                                <tr>
                                    <td>{!! $user->id !!}</td>
                                    <td>{!! $user->name !!}</td>
                                    <td>{!! link_to("mailto:".$user->email, $user->email) !!}</td>
                                    <td>{!! $user->confirmed_label !!}</td>
                                    <td>
                                        @if ($user->roles()->count() > 0)
                                            @foreach ($user->roles as $role)
                                                {!! $role->name !!}<br/>
                                            @endforeach
                                        @else
                                            None
                                        @endif
                                    </td>
                                    <td>
                                        @if ($user->permissions()->count() > 0)
                                            <a href="javascript:;" data-id="{{$user->id}}" role="button"  class="btn btn-xs red findOtherPermissions">View</a>
                                        @else
                                            <button class="btn btn-xs btn-default disabled">None</button>
                                        @endif
                                    </td>
                                    <td class="visible-lg">{!! $user->created_at->diffForHumans() !!}</td>
                                    <td class="visible-lg">{!! $user->updated_at->diffForHumans() !!}</td>
                                    <td>{!! $user->action_buttons !!}</td>
                                </tr>
                            @endforeach
                        @else
                            <td colspan="9">{{ trans('crud.users.no_deactivated_users') }}</td>
                        @endif
                    </tbody>
                </table>

            </div>
        </div>
        <div class="portlet-title">
            <div class="pull-left">
                <h5 class="block">{!! $users->total() !!} {{ trans('crud.users.total') }}</h5>
            </div>

            <div class="pull-right">
                {!! $users->render() !!}
            </div>
        </div>

    </div>
    <div class="clearfix"></div>
    <div id="myModal2" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">Other Permissions</h4>
                </div>
                <div class="modal-body">
                    <p class="per_content">
                        Permissions loading
                    </p>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn green">OK</button>
                </div>
            </div>
        </div>
    </div>
@stop
@section('js')
    <script src="{{asset('backend/js/plugins/userIndex.js')}}" type="text/javascript"></script>
@stop